"System Configuration" label & dynamic release string, "Why OpenIndiana and illumos?" paragraph
OpenIndiana/openindiana-welcome pull request #10
Opened 2018-12-03 08:27 UTC by Mno-hime

Paragraph based on @alarcher's Phoronix forum post.

Other language pages weren't updated.

2018-12-03 08:40 UTC, Mno-hime commented
`openindiana-about` screenshot: https://paste.ec/paste/FlWCNrTQ#DcKO93EcpXDoEjEDy5o2PzTxQwS-upc1pycwqZHiDHD

2018-12-03 18:20 UTC, pyhalov commented on src/openindiana-about.py
> +	file_buffer = open("/etc/release", "r").readlines()[0].strip()
Should we catch open() exceptions here?

2018-12-03 18:24 UTC, pyhalov commented
@Mno-hime Can you find some native speaker to read out text? Also, what are we going to do with current translations?

2018-12-04 08:44 UTC, Mno-hime commented
Email sent to -discuss about the English text. I also asked for other native language speakers' help. But I think we should ship the updated English text regardless the availability of updated translations, once the English text is deemed OK.

2018-12-04 17:17 UTC, notklaatu requested changes
Saw a request for review on the mailing list. I'm a native English-speaker, so I've suggested some minor changes; some are technical, others colloquial.

2018-12-04 17:17 UTC, notklaatu commented on data/html/en/index.html
> +<p>OpenIndiana is an illumos based Unix distribution derived from OpenSolaris.
```suggestion
<p>OpenIndiana is an illumos-based Unix distribution derived from OpenSolaris.
```

2018-12-04 17:17 UTC, notklaatu commented on data/html/en/index.html
> +Engineered as a general-purpose operating system with enterprise-class features,
```suggestion
Engineered as a general purpose operating system with enterprise-class features,
```

2018-12-04 17:17 UTC, notklaatu commented on data/html/en/index.html
> +by Sun Microsystems (now Oracle Corporation) to produce OpenSolaris, a community
```suggestion
by Sun Microsystems (now Oracle Corporation) to produce OpenSolaris, a community-developed
```

2018-12-04 17:17 UTC, notklaatu commented on data/html/en/index.html
> +developed Unix distribution based on Sun Solaris. Project Indiana was led by
```suggestion
Unix distribution based on Sun Solaris. Project Indiana was led by
```

2018-12-04 17:17 UTC, notklaatu commented on data/html/en/index.html
> +    <td>Copy-on-write file system and logical volume manager with extensive data corruption protection, high storage capacities support, efficient data compression, snapshots, and more</td>
```suggestion
    <td>Copy-on-write file system and logical volume manager with extensive data corruption protection, high storage capacity support, efficient data compression, snapshots, and more</td>
```

2018-12-04 17:17 UTC, notklaatu commented on data/html/en/index.html
> +    <td>Hardware-assisted virtualization infrastructure ported from Linux allowing unmodified operating system guests</td>
```suggestion
    <td>Hardware-assisted virtualization infrastructure ported from Linux, allowing unmodified operating system guests</td>
```

2018-12-04 17:17 UTC, notklaatu commented on data/html/en/index.html
>      <td>Automated ZFS Snapshots and Rollbacks</td>
```suggestion
    <td>Automated ZFS snapshots and rollbacks</td>
```

2018-12-04 17:17 UTC, notklaatu commented on data/html/en/index.html
> +with tight coupling between kernel and userspace tools, therefore technologies
```suggestion
with tight coupling between kernel and userspace tools, so technologies
```

2018-12-04 17:17 UTC, notklaatu commented on data/html/en/index.html
> +are very well integrated with each other:</p>
```suggestion
are well integrated with each other:</p>
```

2018-12-04 17:17 UTC, notklaatu commented on data/html/en/index.html
> +  <li>When operating system is updated by the IPS package management system,
```suggestion
  <li>When the operating system is updated by the IPS package management system,
```

2018-12-04 17:17 UTC, notklaatu commented on data/html/en/index.html
> +    ZFS features like Boot Environment and snapshots are leveraged in every
```suggestion
    ZFS features, such as Boot Environment and snapshots, are leveraged in every
```

2018-12-04 17:17 UTC, notklaatu commented on data/html/en/index.html
> +    respect of the process.</li><br>
```suggestion
    aspect of the process.</li><br>
```

2018-12-04 17:17 UTC, notklaatu commented on data/html/en/index.html
> +  <li>When Global Zone is updated, IPS makes sure, that packages
```suggestion
  <li>When the Global Zone is updated, IPS ensures that all packages
```

2018-12-04 17:17 UTC, notklaatu commented on data/html/en/index.html
> +    and <tt>ipmon</tt> have <tt>-z</tt> option, which enables them to operate on a particular Zone without the need
```suggestion
    and <tt>ipmon</tt> have <tt>-z</tt> option, enabling them to operate on a particular Zone without the need
```

2018-12-04 17:17 UTC, notklaatu commented on data/html/en/index.html
> +    to login to the Zone first.</li><br>
```suggestion
    to log in to the Zone first.</li><br>
```
<!-- ("login" is a noun, "log in" is the verb form) -->

2018-12-04 17:17 UTC, notklaatu commented on data/html/en/index.html
> +had contributed in a notable extent to operating system's innovation. Hence we still strive
```suggestion
has made significant contributions to operating system innovation. We continue to strive
```

2018-12-04 17:17 UTC, notklaatu commented on data/html/en/index.html
> +<p>Because our success as a operating system distribution depends upon the success of our community,
```suggestion
<p>Our success as an operating system distribution depends upon the success of our community.
```

2018-12-04 17:17 UTC, notklaatu commented on data/html/en/index.html
> +please, feel welcome in our mailing lists, IRC channels, and GitHub projects.</p>
```suggestion
We want all contributors and users to feel welcome in our mailing lists, IRC channels, and GitHub projects.</p>
```

2018-12-04 17:17 UTC, notklaatu commented on data/html/en/index.html
> +on Linux, Microsoft Windows, and Apple macOS via VirtualBox.</p>
```suggestion
on Linux, Microsoft Windows, and Apple macOS with VirtualBox.</p>
```

2025-01-20 10:01 UTC, closed without merging